

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba(44,37,37,1.0)
    path = /usr/share/wallpapers/cachyos-wallpapers/GreenNekoLady.png
    blur_passes = 3
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 700, 120
    position = 0, 0
    halign = center
    valign = center

    inner_color = rgba(44,37,37,0.8)
    outer_color = rgba(230,217,219,1.0)
    outline_thickness = 4

    font_family = MesloLGL Nerd Font Mono
    font_color = rgba(230,217,219,1.0)

    placeholder_text = Password / 
    check_color = rgba(243,141,112,1.0)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = true
}
